### ISSUE TITLE
Support collapsing of SimplePanel

### ISSUE THREAD

**Issue by ryon** [SlateFoundation/slate-cbl#106]

**Comment by ChrisHoopes** [comment]
@ryon is this still an issue? We're moving things to Jira and I have no idea what this is.

**Comment by katjost** [comment]
Met on 3/2 and decided to close this.

**Comment by themightychris** [comment]
These are examples of simplepanel, these particular ones have a manually implemented collapse behavior on top with no visual indication

![image](https://user-images.githubusercontent.com/458494/109697960-da9f1b00-7b5c-11eb-8181-3b3b1b681237.png)
