### ISSUE TITLE
Develop basic tests for each Slate* app

### ISSUE THREAD

**Issue by themightychris** [SlateFoundation/slate-cbl#112]
Using the testing suite for the AggregridExample app as a model, create a test suit for each of these apps:
- SlateDemonstrationsTeacher (currently broken, see #113)
- SlateDemonstrationsStudent
- SlateTasksTeacher
- SlateTasksStudent

For this scope of this initial pass, just test that the app exists and check that the number of elements in each store or static dataset match the number of elements rendered.

**Comment by themightychris** [comment]
@aliyeysides have you started working on this yet? I don't see any commits or branches

**Comment by aliyeysides** [comment]
@themightychris  yeah sorry, I didn't see this comment.
