### ISSUE TITLE
Wire aggregrid to support example app

### ISSUE THREAD

**Issue by themightychris** [SlateFoundation/slate-cbl#115]
- [x] Map data records to column/row matrix
- [ ] Handle dataStore add/remove/update events to incrementally update aggregate groups
- [ ] execute optional cellTpl and patchFn on group changes 
- [ ] Validate lifecycle variations of dataStore being set/loaded/changed
- [ ] Add support for row rollups

**Comment by katjost** [comment]
Met on 3/2 and decided to keep this open.
