### ISSUE TITLE
Re-implement content-area/students selectors and remove hardcoded data

### ISSUE THREAD

**Issue by themightychris** [SlateFoundation/slate-cbl#129]
In the old setup for the two existing slate-cbl screens, rather than using applications to build and launch UIs we had a bunch of views in the slate-cbl package that some frontend code loaded and rendered views from.

That old technique used the templates at `html-templates/cbl/*-dashboard.tpl` to render a frame for and some basic UI elements outside of the sencha UI. We also embedded some data in the session and from query params set by those non-sencha UIs. The `sencha-workspace/pages/src/page/*.js` scripts handled instantiating the views and loading the embedded data into stores.

The code from those javascripts got moved into the Viewport controllers I started both Demonstrations apps out with, and in some cases i hardcoded data into the index.html files for the apps and hardcoded data into those calls.

We want to:
- [x] Clear out all the hardcoded data
- [ ] Implement the selectors as sencha UI docked to the top of the Dashboard views instead
- [ ] Populate the selectors and load data into the sencha UI following their selections via XHR api calls instead

**Comment by themightychris** [comment]
In the old setup for the two existing slate-cbl screens, rather than using applications to build and launch UIs we had a bunch of views in the slate-cbl package that some frontend code loaded and rendered views from.

That old technique used the templates at `html-templates/cbl/*-dashboard.tpl` to render a frame for and some basic UI elements outside of the sencha UI. We also embedded some data in the session and from query params set by those non-sencha UIs. The `sencha-workspace/pages/src/page/*.js` scripts handled instantiating the views and loading the embedded data into stores.

The code from those javascripts got moved into the Viewport controllers I started both Demonstrations apps out with, and in some cases i hardcoded data into the index.html files for the apps and hardcoded data into those calls.

We want to:
- [ ] Clear out all the hardcoded data
- [ ] Implement the selectors as sencha UI docked to the top of the Dashboard views instead
- [ ] Populate the selectors and load data into the sencha UI following their selections via XHR api calls instead

**Comment by aliyeysides** [comment]
@themightychris could you explain the second bullet? What do you mean by 'docked to the top of the Dashboard views'?

**Comment by ChrisHoopes** [comment]
@BillClinton moved to Jira

**Comment by katjost** [comment]
This is done.
