### ISSUE TITLE
Re-apply grid-multisearch style customizations

### ISSUE THREAD

**Issue by themightychris** [SlateFoundation/slate-cbl#143]
I spun out the grid-multisearch plugin into a private standalone repository

The changes you made here: https://github.com/JarvusInnovations/saki-grid-multisearch/commit/5f6e2df4a6fe388f64a1036f64fe707aa7231f5e

I had to revert here: https://github.com/JarvusInnovations/saki-grid-multisearch/commit/cd5d504582cb356ce21530997c20bb6004c46b92

Because you're making use of variables within a generic ext-classic package that don't exist in ext-classic. You need to re-apply all your improvements but split them in two:
- General improvements to the multisearch scss can be made to our fork, but you can't use custom variables we declare within our apps
- Application of any app-level custom variables needs to be done within the app's scss somewhere as overrides

If you need to work setting from the app-level into the multisearch package's scss, consider adding variables prefixed with grid-multisearch within the package with defaults and then overridding them in the app

**Comment by ryon** [comment]
@themightychris Can you review?

4add8854c30a18cd4164f426dfed60c3a8ccfc05
https://github.com/JarvusInnovations/saki-grid-multisearch/commit/ed2e2997c9e21df39a5ae17e35356435e72b6c0f

**Comment by ChrisHoopes** [comment]
@themightychris is this done and can it be closed out? We're doing housecleaning and moving stuff over to Jira

**Comment by katjost** [comment]
This was done.
