### ISSUE TITLE
Review all scss remaining in slate-cbl package

### ISSUE THREAD

**Issue by themightychris** [SlateFoundation/slate-cbl#144]
@aliyeysides has migrated most views from  the `slate-cbl` sencha package that were only used by one app into that respective app, but it looks like some SCSS may be lingering. Please review all scss files remaining in the slate-cbl package, delete any that is redundant, and finish migrating any that is app-specific to ensure the scss follows its components

**Comment by ChrisHoopes** [comment]
@ryon can you please review the status of this issue and close if no longer relevant
