### ISSUE TITLE
Competency Reports Error

### ISSUE THREAD

**Issue by ckunkel** [SlateFoundation/slate-cbl#145]
The competencies exports on Building 21's site (both Ferguson and Allentown) are not pulling the correct data. Examples below 

Report - http://ferguson.b-21.org/cbl/exports/competencies?students=group+class_of_2019
Dany Villanueva - History content area has 2 logs and 2 Ms in the interface (http://ferguson.b-21.org/cbl/teacher-dashboard?students=section+HISSTUDIO1-9&content-area=HIS) but in the competencies export, he has 29 logged, 0 total and 2 average. 

The competencies export also has columns at the end with no headers, so it seems like they are at best misaligned but also likely not generating the right data. Screen shot of the columns below. 

<img width="971" alt="screen shot 2016-06-08 at 6 54 07 pm" src="https://cloud.githubusercontent.com/assets/5123794/15913839/7c6bbe58-2daa-11e6-9ecf-8561757168d2.png">

**Comment by BillClinton** [comment]
@ckunkel the columns pictured above are not missing column headers on my end, so that may be an issue unrelated to the discrepencies see between the report and the export.  (I am using Libre Office Calc to view the data.)

**Comment by ckunkel** [comment]
@BillClinton the columns look aligned correctly now on Ferguson staging but not all the data is making sense. As I was reviewing, I noticed a separate issue with the Grade Level fields and missing demonstrations, which I'll log separately.

**Comment by ChrisHoopes** [comment]
@BillClinton moved to Jira

**Comment by themightychris** [comment]
This appears to be resolved
