### ISSUE TITLE
Content Area Report Creation

### ISSUE THREAD

**Issue by ckunkel** [SlateFoundation/slate-cbl#147]
A new data export is needed around Content Area progress. An example is Option B (tab B) in this doc https://docs.google.com/spreadsheets/d/1J2R8n44RC_IZsx3FgtYdiG2CpcRoxzlvWSrnP4fkgpI/edit#gid=576915471 
- Each student should show on the report once for each Portfolio (level) for each content area (ie ELA 9 and ELA 10 both show)
- Performance Level is calculated as the average rating of all demonstrations in that content area in that Portfolio. This is similar to the average score for each competency, but is an average across all of them. Note that it's not a straight average of all competencies because competencies have different number of skills. 
- Growth is calculated as the abs(average min score of all skills - average max score of all skills) . Skills with only one evidence requirement are NOT counted as 0 in the average and are instead left out.
- Progress is calculated as a percent. It is the total pieces of evidence completed in the entire content area divided by the number of evidence requirements completed. Overrides can count as multiple pieces of evidence if multiple remain when it is submitted (like they do in the interface).
- Missed Opportunities is calculated as a percent. It is the # of demonstrations missing (logged as an M) divided by the total evidence requirements completed. Overrides can count as multiple pieces of evidence if multiple remain when it is submitted (like they do in the interface).

**Comment by ChrisHoopes** [comment]
@BillClinton moved to Jira

**Comment by katjost** [comment]
This is done.
