### ISSUE TITLE
Scaffold backend data model for Student Tasks

### ISSUE THREAD

**Issue by ChrisHoopes** [SlateFoundation/slate-cbl#149]
When a task is created and assigned we'll need records created for each student that tasks is given to. For this we'll need a table that associates tasks with students and contains fields (set to null by default) for any overridable fields for each student.
### TaskID
- type: integer
### StudentID
- type: integer
### ExperienceType
- type: enum
- default: null
### DueDate
- type: timestamp
- default: null
### ExpirationDate
- type: timestamp
- default: null

**Comment by nbey** [comment]
I need the different values for the `ExperienceTask` enum. Also, are you sure we want to allow `TaskID` / `StudentID` to be null?

**Comment by ChrisHoopes** [comment]
Took care of this on Slack. Enums are found in project, removed nulls.

**Comment by ChrisHoopes** [comment]
@nbey I'm assigning this to @BillClinton as well since he'll need this to get started on the assigned tasks in the student grid. Please work together to get this implemented
