### ISSUE TITLE
Competencies export Grade Level error 

### ISSUE THREAD

**Issue by ckunkel** [SlateFoundation/slate-cbl#154]
On Ferguson staging, the competencies export produces grade levels of 1-8 while none of the students in the school have any logs to target levels other than 9-11. The rows for each grade level should show based on whether any row in the demonstration_skills table has that target level for a given student. For example, if a student has one target level of 8, the entire Grade Level 8 row should appear in the export. The database currently does have some TargetLevels of null, but all of those are missing demonstrations, so it may or may not be related.

<img width="1026" alt="screen shot 2016-06-15 at 9 22 39 am" src="https://cloud.githubusercontent.com/assets/5123794/16081450/736e40d8-32db-11e6-94d7-6090853f58f8.png">

Further, the ELA Missing numbers are incorrect at many students and many levels. This may be the reason the lower grade levels are showing up, but there are no missing logs at those levels that should be generating any numbers, much less numbers so large. 

<img width="984" alt="screen shot 2016-06-15 at 9 26 53 am" src="https://cloud.githubusercontent.com/assets/5123794/16081447/71b3a148-32db-11e6-811e-dbe04fe27cf3.png">

**Comment by ChrisHoopes** [comment]
@BillClinton moved to Jira

**Comment by katjost** [comment]
This export is not used per Tom.
