### ISSUE TITLE
Populate grid with Tasks

### ISSUE THREAD

**Issue by ChrisHoopes** [SlateFoundation/slate-cbl#156]
Populate the Tasks Manager grid with tasks loaded from the database instead of hardcoded sample data.

Once real data is showing up make sure that pagination and column sorting is working correctly. I believe this might be already done via the implemented classic theme table.

**Comment by themightychris** [comment]
@nbey /table_manager can generate the ExtJS model code for you, the `emergence-apikit` and proxy/api wrappers for it contained in the `slate-core-data` package should do most of the work for you.

**Comment by nbey** [comment]
@ChrisHoopes Which field populates the `Year` column?

**Comment by ChrisHoopes** [comment]
@nbey We spoke offline about this but that field should be removed from the grid

**Comment by ChrisHoopes** [comment]
Tasks are now populating from database
