### ISSUE TITLE
Implement grid search

### ISSUE THREAD

**Issue by ChrisHoopes** [SlateFoundation/slate-cbl#157]
Users should be able to search by task title, parent task title, type of experience, skills, year, created by, and/or created date.

I believe some part of this functionality might already be built into the classic grid with the sortable/searchable column headers.

**Comment by themightychris** [comment]
@nbey i think this _should_ Just Work via emergence-apikit if you enable remote filtering on the store and define matching searchConditions on the backend model

**Comment by nbey** [comment]
@ChrisHoopes Can you confirm which search fields should be text vs combo (dropdown)?

@themightychris RE: filter combo stores -- Do you suggest I create endpoint(s) for getting distinct field values? Or should I eliminate the extra calls, and create these stores client-sided by appending the distinct field values to query requests? (Could allow for combo filter values to be filtered with subsequent calls)

**Comment by ChrisHoopes** [comment]
@nbey we'll do all text for now for the search boxes

**Comment by ChrisHoopes** [comment]
@nbey please let me know when I can test this. It should be up and working once any sort of sample data is loaded in right?

**Comment by nbey** [comment]
@ChrisHoopes  This should be ready for testing as well. I'd suggest using the `dev-cbl-tasks` api while testing.

**Comment by ChrisHoopes** [comment]
Bingo
