### ISSUE TITLE
Implement task editing

### ISSUE THREAD

**Issue by ChrisHoopes** [SlateFoundation/slate-cbl#159]
Repurpose the Create Task popup to allow for editing of tasks. No new fields are needed from the Create Task window but there are informational notifications needed which you can see in the below screenshots:
![screen shot 2016-06-16 at 4 03 08 pm](https://cloud.githubusercontent.com/assets/966589/16131473/4e16568e-33dc-11e6-80d8-0accfa7d562d.png)
![screen shot 2016-06-16 at 4 03 21 pm](https://cloud.githubusercontent.com/assets/966589/16131476/51f05c6e-33dc-11e6-8fff-8ca4314c2c6c.png)
![screen shot 2016-06-16 at 4 03 30 pm](https://cloud.githubusercontent.com/assets/966589/16131481/5574af2a-33dc-11e6-8edd-4922ae9dc2fb.png)
![screen shot 2016-06-16 at 4 03 37 pm](https://cloud.githubusercontent.com/assets/966589/16131488/589bc9fe-33dc-11e6-8bea-89c442c649e8.png)

**Comment by nbey** [comment]
Still needs to be worked on:
- [x] Close Editor after saving
- [x] Validation / Validation Errors
- [ ] Attachment Options
- [ ] Configure "Add Task to Database" checkbox

**Comment by ChrisHoopes** [comment]
@nbey as per 172 change "Add Task to Database" to "Share With Other Teachers" defaulted to on. This will mark a task as either private or public (viewable only to the teacher who created it vs all teachers)
