### ISSUE TITLE
Create basic dash with list of tasks

### ISSUE THREAD

**Issue by ChrisHoopes** [SlateFoundation/slate-cbl#163]
On a per-section basis students should be able to view all of their assigned tasks and subtasks. The first step in building out the Student Task Dashboard will be listing all of these out with their relevant details and statuses.

Screenshot of task list below:
![screen shot 2016-06-29 at 3 33 31 pm](https://cloud.githubusercontent.com/assets/966589/16465945/3f3cbfb2-3e0f-11e6-894c-85667c50ded7.png)

**Comment by ChrisHoopes** [comment]
@aliyeysides updated with screenshot, no idea why that didn't save before. Let me know if you have any questions or when there's a first pass to review

**Comment by BillClinton** [comment]
Basic functionality complete.  There are still a few issues to work out in order to complete communication with API.

**Comment by ChrisHoopes** [comment]
@BillClinton what are the issues exactly?
