### ISSUE TITLE
Style TasksDatabase header and button

### ISSUE THREAD

**Issue by ChrisHoopes** [SlateFoundation/slate-cbl#165]
Style the TasksDatabase app header and button (create, edit, delete) to match the designs. These were created in this issue: https://github.com/SlateFoundation/slate-cbl/issues/155

See screenshot below for design:
![screen shot 2016-06-16 at 3 19 24 pm](https://cloud.githubusercontent.com/assets/966589/16130173/f7cfaf60-33d5-11e6-9cc1-f875580a629a.png)

**Comment by ryon** [comment]
Since these headers should be appearing all throughout the UI, I defined and styled a new AppHeader class here 0348ad5486c151c4231719bb830c7a91c0478715. Right now it doesn't really do anything but offer a common target for styling. Would be nice if it could take a title config, maybe.
