### ISSUE TITLE
Allow expansion of tasks to view subtasks

### ISSUE THREAD

**Issue by ChrisHoopes** [SlateFoundation/slate-cbl#166]
This is covered a bit by https://github.com/SlateFoundation/slate-cbl/issues/163 but tasks need to be expandable to show sub-tasks. This is allowed both when they're in-progress and when submitted.

Screenshot of tasks with expanded subtasks below:
![screen shot 2016-06-29 at 3 33 31 pm](https://cloud.githubusercontent.com/assets/966589/16465945/3f3cbfb2-3e0f-11e6-894c-85667c50ded7.png)

**Comment by ChrisHoopes** [comment]
@BillClinton this can be marked complete, no?

**Comment by BillClinton** [comment]
@ChrisHoopes Yes, This is complete.
