### ISSUE TITLE
Enable tasks selection to view details

### ISSUE THREAD

**Issue by ChrisHoopes** [SlateFoundation/slate-cbl#167]
Students should be able to select a task to view all of its details. These include:
- title
- parent tasks
- type of experience
- due date
- expiration date
- related documents
- submitted date
- attached documents and folder
- skills and teacher comments

See screenshot below for design:
![screen shot 2016-06-29 at 3 49 58 pm](https://cloud.githubusercontent.com/assets/966589/16466554/90dc840e-3e11-11e6-8f86-88de5b24c831.png)
![screen shot 2016-06-29 at 3 50 08 pm](https://cloud.githubusercontent.com/assets/966589/16466558/9407460a-3e11-11e6-923a-988ab12a01e3.png)

**Comment by ChrisHoopes** [comment]
@aliyeysides let's focus first on getting the basic information filled in and then moving on to attachments and other more complicated bits of this functionality. Please let me know if you have any questions.

**Comment by ChrisHoopes** [comment]
@BillClinton just a note that this should be ready to be worked on as per our call the other day

**Comment by BillClinton** [comment]
@ChrisHoopes This has been implemented.
