### ISSUE TITLE
Style popups to match designs

### ISSUE THREAD

**Issue by ChrisHoopes** [SlateFoundation/slate-cbl#168]
Style the implemented popups to match the designs in InVision. To get the app working, pull down the most recent version, navigate to SlateTasksManager, and use ?apiHost=dev-cbl-tasks.node0.slate.is

I'm not sure what happened to the rest of the comment on this issue but please see attached screenshot for what it should look like:
![screen shot 2016-07-05 at 10 16 19 am](https://cloud.githubusercontent.com/assets/966589/16624338/43c5e878-436f-11e6-855c-57a19e2f3894.png)

**Comment by ChrisHoopes** [comment]
@ryon updated with screenshot

**Comment by ryon** [comment]
Windows styled via f857a4dda111ca821425cb26127d6beb90ecabec, 1af34524f1136dde2984f74604a18e51ed1a2005, 0ddfb1b394a719279e4490ec71c5b3678e0ed592

I'd like to leave label styling as-is to better match the rest of Slate.
