### ISSUE TITLE
Type of Experience should take any value

### ISSUE THREAD

**Issue by ChrisHoopes** [SlateFoundation/slate-cbl#179]
Change Type of Experience from an enum to a field that can take any string value but recall previously used ones in the dropdown.

This is NOT required for training

**Comment by nbey** [comment]
@ChrisHoopes This should be ready to go, however, the results of what is shown when searching Experience Types is dependent of what's in the database, meaning that the default options (Flex Time, Internship, Studio) may not show up unless they exist in the DB.

**Comment by ChrisHoopes** [comment]
@nbey is there a branch this works on? If I try to type in an arbitrary value it just clears the field as soon as it loses focus if it's not one of the options in the dropdown.

**Comment by nbey** [comment]
@ChrisHoopes This should now be testable in `features/teacher-tasks-manager` branch.

**Comment by ChrisHoopes** [comment]
@nbey still not working for me. I see a note about it in the last commit for origin/issues/179 but it looks like it was never merged back into teacher-tasks-manager?
