### ISSUE TITLE
Write deep tests for aggregrid components

### ISSUE THREAD

**Issue by themightychris** [SlateFoundation/slate-cbl#186]
## Tests
- [ ] Adding, removing, and updating `dataStore` records fires correct events and updates all internal state
- [ ] `dataStore` record can go from phantom to real ID
- [ ] `dataStore` can be set/loaded/changed in any order
- [ ] SlateDemonstrationsTeacher regains full functionality on top of aggregrid
- [ ] Ensure correct number of layout runs through various operations

**Comment by katjost** [comment]
Met on 3/2 and decided to keep this one open.
