### ISSUE TITLE
Update task details for edited task

### ISSUE THREAD

**Issue by ChrisHoopes** [SlateFoundation/slate-cbl#187]
When a task is selected in the grid its attachment and description details are shown in the right column. When you edit a task these details don't update after saving until you click off an back on an issue.

This is extremely minor and not needed for training.

**Comment by nbey** [comment]
@ChrisHoopes This can be qa'd in the by checking out the branch `issues/187`.

**Comment by ChrisHoopes** [comment]
@nbey Task description seems to be saving and updating correctly but on that branch attachments aren't saving at all so I can't test if that's updating in the sidebar

**Comment by ChrisHoopes** [comment]
@nbey 187 has been closed and merged but attachments still aren't updating on save and require a click off and on to update the sidebar. Also for some reason the attachment icons in the list just don't show up sometimes? These are both super low priority.
