### ISSUE TITLE
Increase description line count

### ISSUE THREAD

**Issue by ChrisHoopes** [SlateFoundation/slate-cbl#196]
Increase the amount of lines seen in the description field to 10 for Create and Edit task windows.

**Comment by nbey** [comment]
@ChrisHoopes I believe I can change the size by pixels -- do we want the box to be roughly twice as long?

**Comment by nbey** [comment]
@ChrisHoopes This fix is included in the branch `features/teacher-tasks-manager`. Although the issues are for separate apps, they both are using the same component so it has been fixed in both apps on that branch (which may not be up to date in other aspects).

**Comment by ChrisHoopes** [comment]
Looks good
