### ISSUE TITLE
Allow students to submit tasks for grading

### ISSUE THREAD

**Issue by ChrisHoopes** [SlateFoundation/slate-cbl#200]
Allow students to submit their tasks for teacher grading. This isn't dependent on any attachments being present.

**Comment by BillClinton** [comment]
@ChrisHoopes This has been fixed and is ready for testing/verification.   Students have the ability to add links and submit unless the status of the task is complete

**Comment by ChrisHoopes** [comment]
@BillClinton re-opening this as it seems like there's a major problem with submitting tasks now. When I go to submit a task attachments aren't saved, the screen goes gray for a few seconds, and as far as I can tell nothing has actually been submitted.

**Comment by BillClinton** [comment]
This was an API version control issue.  Code has been restored: /develop#diff:[47764,48834]/php-classes/Slate/CBL/Tasks/StudentTask.php
