### ISSUE TITLE
Don't highlight skill grade before it's been graded

### ISSUE THREAD

**Issue by ChrisHoopes** [SlateFoundation/slate-cbl#210]
By default currently every skill attached to a task is showing a grading of 10 before a teacher has a chance to actually grade the skill. Default it to nothing.

![screen shot 2016-07-25 at 12 46 22 pm](https://cloud.githubusercontent.com/assets/966589/17109391/d5c0acfe-5265-11e6-98e2-22c46083fa54.png)

**Comment by BillClinton** [comment]
@ChrisHoopes this is implemented and ready for testing/closure.  The defaults have been removed and grades are now set using the correct values from the API
