### ISSUE TITLE
Show submitted date after submission

### ISSUE THREAD

**Issue by ChrisHoopes** [SlateFoundation/slate-cbl#211]
After a student submits a task its detail window should show the submitted date in the student section.

**Comment by BillClinton** [comment]
@ChrisHoopes this has been fixed and is ready for verification/closure

**Comment by ChrisHoopes** [comment]
@BillClinton similar to task 200, it appears as though submissions are currently broken.

**Comment by BillClinton** [comment]
@ChrisHoopes Yes, this was the same as issue 200, but I noticed the date in the task tree was always showing DueDate, regardless of status.  I updated it so when a TaskStatus is submitted or re-submitted, it shows Submitted date

**Comment by BillClinton** [comment]
@ChrisHoopes I moved this fix to the features/todo branch because I don't like having multiple branches/PRs with modifcations to the same file  : https://github.com/SlateFoundation/slate-cbl/commit/7cbfc574b17be09942c1ee18582873144993a088
