### ISSUE TITLE
Move toast to middle of the screen

### ISSUE THREAD

**Issue by ChrisHoopes** [SlateFoundation/slate-cbl#212]
Is it possible to have the toast as an actual little popup overlay in the middle of the screen that quickly goes away instead of down in the lower right corner? It's kinda making the user experience with the auto scrolling so they can see it and such.

**Comment by nbey** [comment]
@ChrisHoopes Hmm, I do not believe there is a simple baked-in way to center it completely (vertically/horizontally), however there may be a way to easily anchor it to the top. I found an example of someone showing notifications in various locations ([Ext.ux.Window Demo](http://www.eirik.net/Ext/ux/window/Demo.html))-- this could definitely be used as a point of reference, but it may make sense to consult with @ryon as he may have some insight.
