### ISSUE TITLE
Disable auto scrolling

### ISSUE THREAD

**Issue by ChrisHoopes** [SlateFoundation/slate-cbl#213]
This is something we'll need to do on both the Teacher and the Student app but right now with the giant popovers when tasks have 4+ skills the autoscrolling is kind of a mess. I think the framework is trying to get various elements in the viewport at various times and it just feels broken. Let's talk about this.

**Comment by themightychris** [comment]
As long as we're doing modals that can be bigger than the screen, it's either this or we control the size of the modals and give them internal scrolling somewhere

**Comment by ChrisHoopes** [comment]
@ryon do you have an opinion on this? I'm personally not a fan of internal scrolling in modals but I can see how it can get messy if there's 6+ skills assigned to a task.

**Comment by ryon** [comment]
@ChrisHoopes What do you mean by auto scrolling, exactly? As for the modals, I don't love having them scroll internally either, but it does seem like some of them get too unwieldy without it.

**Comment by ChrisHoopes** [comment]
@ryon there are a number of actions currently that seem to force focus on various parts of the UI, the toast appearing in the lower right is one of them. This is distracting and actively hurts the workflow of the app, that's what I mean.

As for internal scrolling, yeah the more I think on it the more that might be the required path here.

**Comment by ryon** [comment]
@ChrisHoopes Hm ok, I don't think I've observed that behavior personally (I've never witnessed a toast appearing, for example). Doesn't sound great. Is the problem that the user might not see certain notifications otherwise?
