### ISSUE TITLE
Allow viewing of rated tasks

### ISSUE THREAD

**Issue by ChrisHoopes** [SlateFoundation/slate-cbl#219]
Currently after a teacher rates a task they're unable to view its details. Allow the teacher to see task and rating details in a read-only view.

**Comment by ChrisHoopes** [comment]
@nbey after rating a task I can't see the values in the resulting popup

**Comment by nbey** [comment]
@ChrisHoopes I still have not been able to reproduce this, could you provide some more details?

**Comment by ChrisHoopes** [comment]
@nbey as of now on the develop branch you can't view skill ratings until you reload the page
