### ISSUE TITLE
Show status of Rated after teacher rating

### ISSUE THREAD

**Issue by ChrisHoopes** [SlateFoundation/slate-cbl#220]
When a teacher rates a task its status should change to Rated which will allow the student to filter as such. This isn't currently happening.

**Comment by BillClinton** [comment]
@ChrisHoopes I'll tag you tomorrow to discuss this.  I thought skills within tasks were rated, not the tasks themselves.  StudentTasks currently have 5 statuses: ('assigned', 're-assigned', 'submitted', 're-submitted', 'completed')  Should the StudentTask status be changed to "rated" when any skill within that task is rated?  I'll tag and include @nbey as a participant on this he would most likely implement the part of the API that would change the task status upon a teacher action.
