### ISSUE TITLE
Slider isn't colored to current level

### ISSUE THREAD

**Issue by ChrisHoopes** [SlateFoundation/slate-cbl#222]
Ratings slider isn’t colored to current level (neutral or color of due state, not level)

**Comment by ChrisHoopes** [comment]
@ryon if you could please assist Nafis in what color the rating sliders should be. Has this been designed out?

**Comment by ryon** [comment]
@nbey We had talked about this in Slack, I think. Do you still need any help from me? Any missing CSS classes?

**Comment by nbey** [comment]
This should be good to go in the latest branch, `features/teacher-tasks-manager`.
