### ISSUE TITLE
Allow for re-selecting due date on reassign

### ISSUE THREAD

**Issue by ChrisHoopes** [SlateFoundation/slate-cbl#223]
After re-assigning a task and selecting a due date allow for the ability to re-assign again and select a new due date regardless of student action.

**Comment by nbey** [comment]
Could you clarify what you mean? Are you referring to the ability to re-assign a task while it's due (and not _only_ when it has been submitted, and is able to be rated)?

**Comment by nbey** [comment]
@ChrisHoopes This should be configured so that clicking on tasks that are _re-assigned_ shows the **Rate Task** window instead of the **Edit Task** window.
