### ISSUE TITLE
Remove overall progress placeholder

### ISSUE THREAD

**Issue by ChrisHoopes** [SlateFoundation/slate-cbl#230]
Overall Progress is getting completely overhauled so please remove this placeholder for now.

![screen shot 2016-08-01 at 1 37 20 pm](https://cloud.githubusercontent.com/assets/966589/17303114/4edc8cac-57ed-11e6-94a0-f24add95eef1.png)

**Comment by BillClinton** [comment]
This is ready for verification/closure
