### ISSUE TITLE
Create header with Course Section dropdown

### ISSUE THREAD

**Issue by ChrisHoopes** [SlateFoundation/slate-cbl#231]
Mirroring the Teacher app, add matching header with functional Course Section dropdown to change what section a student is currently viewing.

For right now just show all sections until we get student/section associations worked out.

![screen shot 2016-08-01 at 1 41 54 pm](https://cloud.githubusercontent.com/assets/966589/17303295/0f9f5834-57ee-11e6-91ef-17f0bcde9072.png)

**Comment by BillClinton** [comment]
This is ready for verification/closure
