### ISSUE TITLE
Move Recent Activity into header dropdown

### ISSUE THREAD

**Issue by ChrisHoopes** [SlateFoundation/slate-cbl#232]
Recent Activity will be shown/hidden by clicking on the timer icon in the header. For now move the Recent Activity placeholder section into that dropdown.

![screen shot 2016-08-01 at 1 48 19 pm](https://cloud.githubusercontent.com/assets/966589/17303428/a710a4de-57ee-11e6-9051-dc64cf576508.png)

**Comment by BillClinton** [comment]
Ready for verification/closure
