### ISSUE TITLE
Scaffold backend data model for To-Do

### ISSUE THREAD

**Issue by ChrisHoopes** [SlateFoundation/slate-cbl#233]
Students are able to create To-Dos for themselves. These are shown on their dashboard and exist outside the influence of the Current Section dropdown in the header. To-Dos are separated into several lists, one for each course the student is enrolled in and a final personal list that isn't associated with a course.

Each To-Do has five attributes:
- section (can be null for personal)
- description (text)
- due date
- complete boolean
- cleared boolean

The section is determined based on which header you've created the task under. Once a To-Do is created the student cannot edit the description or due date. It is up to the student to mark a To-Do as complete or incomplete. To get rid of the To-Do completely a student can Clear all To-Dos marked as complete for a given section.

This task revolves around setting up the basic To-Do model
### StudentID
- type: integer
### SectionID
- type: integer (nullable for Personal)
### Description
- type: string
### DueDate
- type: timestamp
### Completed
- type: bool
- default: false
### Cleared
- type: bool
- default: false

Ignore the Competencies listed above each To-Do in the designs below:

![screen shot 2016-08-01 at 2 16 47 pm](https://cloud.githubusercontent.com/assets/966589/17304508/e26c187e-57f3-11e6-98bd-deb0e0cbfdb6.png)

**Comment by BillClinton** [comment]
created:
site-root/cbl/todos.php
php-classes/Slate/CBL/Tasks/TodosRequestHandler.php
php-classes/Slate/CBL/Tasks/Todo.php

**Comment by BillClinton** [comment]
@ChrisHoopes API is functioning
