### ISSUE TITLE
Create separate To-Do list for each section

### ISSUE THREAD

**Issue by ChrisHoopes** [SlateFoundation/slate-cbl#235]
For each section a student is currently enrolled in, create a To-Do list in the Student dashboard. At the top of all these add an additional To-Do list for Personal To-Dos that's not associated with any section.

The To-Do lists aren't affected by the section dropdown in the header.

![screen shot 2016-08-02 at 2 23 12 pm](https://cloud.githubusercontent.com/assets/966589/17340127/eb752126-58bc-11e6-904b-b6438e22ef52.png)

**Comment by BillClinton** [comment]
@ChrisHoopes ready for Q&A
