### ISSUE TITLE
Add ability to create To-Dos

### ISSUE THREAD

**Issue by ChrisHoopes** [SlateFoundation/slate-cbl#236]
Allow students to create To-Dos either under the Personal list or within any of the section To-Dos. Each To-Do consists of a text description and a due date. At this time To-Dos cannot be modified, only created, completed, and cleared.

![screen shot 2016-08-02 at 2 25 29 pm](https://cloud.githubusercontent.com/assets/966589/17340194/2a54a8b2-58bd-11e6-8ba3-3233e3f1de61.png)

**Comment by BillClinton** [comment]
@ChrisHoopes ready for Q&A
