### ISSUE TITLE
List items under each To-Do section

### ISSUE THREAD

**Issue by ChrisHoopes** [SlateFoundation/slate-cbl#237]
For each To-Do list (personal and one for each section) list all of the To-Dos created by a student.

![screen shot 2016-08-02 at 2 25 29 pm](https://cloud.githubusercontent.com/assets/966589/17340249/65f6a794-58bd-11e6-8d3a-cb525409bd95.png)

**Comment by BillClinton** [comment]
@ChrisHoopes ready for Q&A
