### ISSUE TITLE
Clicking on To-Do header should hide/show list

### ISSUE THREAD

**Issue by ChrisHoopes** [SlateFoundation/slate-cbl#238]
Students should be able to hide and show a list of To-Dos by clicking on its section header.

![screen shot 2016-08-02 at 2 29 39 pm](https://cloud.githubusercontent.com/assets/966589/17340307/9d7c2b26-58bd-11e6-8394-e72b729be98c.png)

**Comment by BillClinton** [comment]
@ChrisHoopes ready for Q&A
