### ISSUE TITLE
Checking a To-Do should mark it as Completed

### ISSUE THREAD

**Issue by ChrisHoopes** [SlateFoundation/slate-cbl#239]
In each To-Do list, checking off a To-Do should move it down to the Completed Items section. Unchecking should move it back up to the active To-Dos.

![screen shot 2016-08-02 at 2 31 25 pm](https://cloud.githubusercontent.com/assets/966589/17340370/d7546246-58bd-11e6-9ac9-36d116073c3e.png)

**Comment by BillClinton** [comment]
@ChrisHoopes Ready for Q&A
