### ISSUE TITLE
Class for Todo list titles needed

### ISSUE THREAD

**Issue by BillClinton** [SlateFoundation/slate-cbl#242]
The Todo list was originally created to display one set of Todos.  Now, in addition to personal Todos, we wish to display a Todo list for each course section in which the student is enrolled.  Rather than use an instance of the Todo list for each course section which would have required run-time instantiation, I altered the template so the Todo list component can display lists for all course sections.

The header of the Todo lists was previously set by the `title` attribute of the TodoList component.  Now, It is being set in a div within the xtemplate.  I gave the div the class being used by the `Slate.cbl.widget.SimplePanel` Titlebar and it _almost_ works, but the font is smaller.  Can you add a class for titles within a div in the xtemplate that replicates the look of SimplePanel's title header?

Here is where this class would be used:
https://github.com/SlateFoundation/slate-cbl/blob/releases/v2/develop/sencha-workspace/SlateTasksStudent/app/view/TodoList.js#L34

**Comment by BillClinton** [comment]
Here is a comparison:
![todo_titles](https://cloud.githubusercontent.com/assets/1786769/17531414/bcd89482-5e49-11e6-9ac0-51dd3d592214.png)

**Comment by ryon** [comment]
@BillClinton there is already a class `.slate-simplepanel-title`, just needed to add that to the template. Fixed in #298
