### ISSUE TITLE
Need to add space between each To-Do section

### ISSUE THREAD

**Issue by ChrisHoopes** [SlateFoundation/slate-cbl#247]
Currently all of the To-Do lists crowd up on each other vertically. We'll need to add space between each like in the screenshot below:

![screen shot 2016-08-02 at 2 29 39 pm](https://cloud.githubusercontent.com/assets/966589/17340307/9d7c2b26-58bd-11e6-8394-e72b729be98c.png)

Let me know if Ryon should handle this and I'll reassign.

**Comment by BillClinton** [comment]
@hoopes yeah, I think Ryon should create a class for this.  I added inline styles here to approximate what we need: https://github.com/SlateFoundation/slate-cbl/blob/6239b28594c63d022f42be7a85cf7250c6c9ba56/sencha-workspace/SlateTasksStudent/app/view/TodoList.js#L42 and it works for now.

**Comment by BillClinton** [comment]
The way I resolved the space previously did not work on collapsed todo lists because the div with the margin becomes hidden, so I added a wrapper div with bottom-margin: https://github.com/SlateFoundation/slate-cbl/commit/b4a67bd69b20a56f3c57e33eaf901214f4fe385f
