### ISSUE TITLE
Filter tasks and to-dos by section

### ISSUE THREAD

**Issue by ChrisHoopes** [SlateFoundation/slate-cbl#248]
When a student chooses a section in the course dropdown filter the dashboard to show only tasks within that section. For to-dos, only show that section's to-do list along with the personal to-dos.

**Comment by BillClinton** [comment]
@ChrisHoopes This is ready for Q&A

**Comment by ChrisHoopes** [comment]
@BillClinton filtering to-dos seems to initially work but as soon as I add a new to-do, mark one as complete, or take any other action all of the other to-do lists appear until I select another course and it filters again.

**Comment by BillClinton** [comment]
@ChrisHoopes ready for Q&A
