### ISSUE TITLE
Skill not showing in Rate Task window

### ISSUE THREAD

**Issue by ChrisHoopes** [SlateFoundation/slate-cbl#255]
As per Christian, "When a skill hasn’t been rated, it doesn’t show in the Rate task window, which is needed when we are allowing them to rate any skill at any time."

![screen shot 2016-08-16 at 5 22 52 pm](https://cloud.githubusercontent.com/assets/966589/17717685/67784c6e-63dd-11e6-9409-4426a88fc5cf.png)

**Comment by nbey** [comment]
@ChrisHoopes This appears to be an issue with the Students app. I'm working with @BillClinton to get this resolved. In the mean time, I've updated the milestone/assignees accordingly.

**Comment by BillClinton** [comment]
Is this still an issue?

**Comment by nbey** [comment]
@BillClinton I don't believe so.
