### ISSUE TITLE
When no course is selected, show all tasks and To-Dos

### ISSUE THREAD

**Issue by ChrisHoopes** [SlateFoundation/slate-cbl#256]
When a student initially lands on the Student Dashboard there should not be any course selected. When the dash is in this state show all tasks and to-do sections.

**Comment by BillClinton** [comment]
@ChrisHoopes this is ready for Q&A

**Comment by ChrisHoopes** [comment]
@BillClinton found two issues with this at the moment:
- there's currently no way to deselect a course other than reloading the page
- i'm seeing more tasks when all are shown than I am when I go through each of the courses I'm assigned to. Am I seeing tasks from courses that I'm not enrolled in?

**Comment by BillClinton** [comment]
@ChrisHoopes the "all" option in the course selection is ready for Q&A.  Not sure on the extra tasks.  Perhaps make a new issue for that that we can resolve after @nafis latest changes are merged with mine
