### ISSUE TITLE
Add course section to collapsed tasks

### ISSUE THREAD

**Issue by ChrisHoopes** [SlateFoundation/slate-cbl#258]
Instead of the Type of Experience or the examples in the screenshot (MYTHBUSTERS, etc) have that show the task's course section name.

![screen shot 2016-08-18 at 3 25 32 pm](https://cloud.githubusercontent.com/assets/966589/17787728/4af97974-6558-11e6-9578-6fb6bc1ab3d6.png)

**Comment by BillClinton** [comment]
@ChrisHoopes this is added in the features/student-tasks-fixes covered by PR 279 and is ready for Q&A and merging
