### ISSUE TITLE
Reassaign date picker persists after assign window closed

### ISSUE THREAD

**Issue by ChrisHoopes** [SlateFoundation/slate-cbl#259]
If you don't close the date picker before closing the assign window the date picker persist until you click on something. This should close when its parent window is closed.

**Comment by nbey** [comment]
@ChrisHoopes We're moving away from this, by going with the field that I suggested, correct?

**Comment by ChrisHoopes** [comment]
@nbey yes but we'll still have a date picker in the new version. We'll just need to make sure it closes with the parent too.
