### ISSUE TITLE
Don't allow unassign if task is graded

### ISSUE THREAD

**Issue by ChrisHoopes** [SlateFoundation/slate-cbl#267]
I forget how we said we wanted to handle this but we don't want to allow teachers to unassign tasks once a student has submitted it and it's been graded correct? Please let me know when you start this so we can discuss.

**Comment by nbey** [comment]
@ChrisHoopes I believe that's what we discussed, however I mentioned there would be an issue figuring out which student tasks are 'graded', since skills are graded, not tasks, and tasks may contain skills that were rated in a previous task.
