### ISSUE TITLE
Separate assign date picker and assign revision button

### ISSUE THREAD

**Issue by ChrisHoopes** [SlateFoundation/slate-cbl#268]
Instead of having one button to pick a new assign date and then also to save that new date we want to have a field where a teacher can pick a new date and then a dedicated reassign button to save it.

**Comment by nbey** [comment]
@ChrisHoopes This should be good to go now in it's own titled branch.

**Comment by ChrisHoopes** [comment]
The field seems to work but every time I close and re-open the same issue it adds a duplicate set of fields.

![screen shot 2016-08-18 at 10 58 08 pm](https://cloud.githubusercontent.com/assets/966589/17797495/504ce3fe-6597-11e6-8b76-60880168cd1d.png)
