### ISSUE TITLE
Evidence requirement boxes become one big box after logging a demonstration in that standard

### ISSUE THREAD

**Issue by jcunn302** [SlateFoundation/slate-cbl#41]
Steps to reproduce:
1. Navigate to the teacher dashboard and filter to a group and content area.
2. Click an empty evidence requirement box/cell
3. Click log a demonstration
4. Add another competency to the demonstration & rate at least one standard in each.
5. Uncheck load next student

Actual Result:
While the main competency % complete and progress bar updates, the evidence requirements box/cell becomes one long one. (Only happens for the initial standard selected for log a demo)

Expected Result:
Evidence requirement cells should retain their dividers and the first box should fill with the info from the recently logged demo.

![screen shot 2015-05-06 at 6 28 27 pm](https://cloud.githubusercontent.com/assets/1789284/7505183/5a582f2a-f41e-11e4-9ad7-ba7f84f66692.png)

**Comment by jcunn302** [comment]
Update: This occurs on editing demonstrations, as well.

**Comment by themightychris** [comment]
fixed in newer builds of the levels branch
