### ISSUE TITLE
DemonstrationsTeacher - Unrated skills should be white, not grey

### ISSUE THREAD

**Issue by ckunkel** [SlateFoundation/slate-cbl#413]
Unrated skills in the teacher grid should be white rather than grey styling. 

![screen shot 2018-01-22 at 4 03 59 pm](https://user-images.githubusercontent.com/5123794/35244360-e09c52be-ff8d-11e7-8c31-8333052a5c63.png)

**Comment by themightychris** [comment]
The "uncounted" class may be getting inappropriately applied here as the opposite of "counted" when it should only be applied maybe in the case of missing assignments. The student UI was applying an "uncounted" class for all non-counted ones so I replicated that behavior here and it turned all these grey from white

**Comment by ckunkel** [comment]
Ok. That makes sense.

**Comment by themightychris** [comment]
that was some context for @ryon as I'm not sure whether the best resolution is changing the applied classes or restyling them

**Comment by ryon** [comment]
Fixed in d8d2cce34925a61c1933049bfaea6eb2f0719a5c

![screen shot 2018-01-26 at 5 36 49 pm](https://user-images.githubusercontent.com/1154929/35463639-9ade876c-02bf-11e8-9dff-8f55850243c0.png)
