### ISSUE TITLE
DemonstrationsStudent (teacher view) - Standard Overview window styling

### ISSUE THREAD

**Issue by ckunkel** [SlateFoundation/slate-cbl#414]
The Competency selector dropdown cuts off text and has nothing selected initially. Layout should be updated to accommodate text and the selector should have the relevant competency populated. 

![screen shot 2018-01-22 at 4 05 40 pm](https://user-images.githubusercontent.com/5123794/35244439-1f356d9e-ff8e-11e7-81ab-16176b7c1d55.png)
![screen shot 2018-01-22 at 4 05 33 pm](https://user-images.githubusercontent.com/5123794/35244441-1f3ecdd0-ff8e-11e7-92bf-5ff041508d06.png)

**Comment by themightychris** [comment]
This was fixed in a33f30727b91dfab3158663922e2212c89c5675f and is already on cbl-qa
