### ISSUE TITLE
DemonstrationsStudent - Recent Progress handling of Overrides

### ISSUE THREAD

**Issue by ckunkel** [SlateFoundation/slate-cbl#415]
The Recent Progress area currently shows Overrides as M rather than O. This is viewable by selecting an Overridden skill to see the history and comparing it to what is listed in Recent Progress. 

![screen shot 2018-01-22 at 4 08 12 pm](https://user-images.githubusercontent.com/5123794/35244541-7a304a7a-ff8e-11e7-8510-2119d8943319.png)
![screen shot 2018-01-22 at 4 08 00 pm](https://user-images.githubusercontent.com/5123794/35244542-7a3f9af2-ff8e-11e7-880a-2720cb5e5ac2.png)
![screen shot 2018-01-22 at 4 07 51 pm](https://user-images.githubusercontent.com/5123794/35244543-7a478af0-ff8e-11e7-8349-41f5ddeaf95d.png)

**Comment by themightychris** [comment]
@ckunkel should we keep the "O" in the competency card or change that to a dash? I worry about the "O" being interpreted as a zero

**Comment by ckunkel** [comment]
Check-circle-o in font awesome (same as in student dashboard used for skill completion)

**Comment by themightychris** [comment]
circle-o is everywhere now in 1266b45adbb8d5d0a6b5aa16f13158ea3e932240 and built to cbl-qa

![image](https://user-images.githubusercontent.com/458494/35364180-b7d5560a-013b-11e8-934e-7726e12ff54c.png)

![image](https://user-images.githubusercontent.com/458494/35364189-c5e741f4-013b-11e8-8b88-05209cce5ab5.png)

![image](https://user-images.githubusercontent.com/458494/35364207-d946399e-013b-11e8-9266-8379ff9da1a1.png)

![image](https://user-images.githubusercontent.com/458494/35364275-39fbe176-013c-11e8-9041-c703f5eac640.png)

I also replaced the existing circle checkbox that was an inline svg w/ a border with the same font-awesome icon for consistency

Assigning to @ryon for a visual review as I'm wondering if the contrast in boldness between the check mark and the numbers in some places is a bit too extreme.

**Comment by ryon** [comment]
The visual weight is a bit distracting, and if I reduce the size of the glyph it becomes hard to read. I can't do much about the weight itself other than draw a new icon from scratch.

Would it be confusing if we used a circle-less check mark instead?

![screen shot 2018-01-26 at 4 51 20 pm](https://user-images.githubusercontent.com/1154929/35462316-6d88e04c-02b9-11e8-89a8-f7ef9335b3f2.png)
![screen shot 2018-01-26 at 4 50 52 pm](https://user-images.githubusercontent.com/1154929/35462317-6d932ae8-02b9-11e8-888c-4169a3b7819d.png)

**Comment by ryon** [comment]
We could take the balancing even further and bump up the weight of the numbers a bit. This would be a bit drastic as it would apply in a _lot_ of places, but I might be ok with it...?

![screen shot 2018-01-26 at 5 01 44 pm](https://user-images.githubusercontent.com/1154929/35462606-a6642268-02ba-11e8-9158-2f4438c2db37.png)
![screen shot 2018-01-26 at 5 01 22 pm](https://user-images.githubusercontent.com/1154929/35462607-a67115f4-02ba-11e8-8160-49d8a859b5b7.png)

**Comment by ckunkel** [comment]
I like how you handled that. Using the circle for the overall skill and just the check for the cell looks very clean and logical.

**Comment by ryon** [comment]
OK, 1911bedc1c208dc75a0e699a2f70bf67be970579 implements this change (plain checkmarks instead of circled in most places, bolder-looking numbers to match). It's very possible I missed some, so let me know if you spot any that need to be changed.

**Comment by themightychris** [comment]
@ryon did you commit the increased weight for the numbers? I liked that but don't see it in the commits. I think we only have to worry about applying it in the places with the level-colored cells, the 4 places I originally screenshotted to highlight where the check-circle got placed should be all we need to worry about

@ckunkel what do you think about the increased weight shown in Ryon's last screenshots?

**Comment by ryon** [comment]
@themightychris I did check it in, but it's not exactly increased weight. I just switched the antialiasing method for those numbers, which may or may not have an effect in various browser/OS combinations (it's a nonstandard property).

**Comment by ckunkel** [comment]
@themightychris the increased weight looks good.
