### ISSUE TITLE
DemonstrationsStudent - inconsistent styling of ratings in cell

### ISSUE THREAD

**Issue by ckunkel** [SlateFoundation/slate-cbl#416]
In the Recent Progress section, the styling of the ratings in the center of the cell differ from those used in the skill rating fields because they lack a dropshadow. The same styling should be used in both places. 

![screen shot 2018-01-22 at 4 10 20 pm](https://user-images.githubusercontent.com/5123794/35244622-c4be5afa-ff8e-11e7-99de-68ad3a954000.png)

**Comment by ryon** [comment]
Fixed in 89efc76f5ff1eae4fe0905e2533fbdf27dfd1990. I also tweaked the spacing a bit for readability, and brought back shadows for panel titles.

![screen shot 2018-01-26 at 5 01 22 pm](https://user-images.githubusercontent.com/1154929/35463671-cd9b4b40-02bf-11e8-82c3-563907918e59.png)
