### ISSUE TITLE
DemonstrationsStudent (as a student) - Standard Overview Window lacks data

### ISSUE THREAD

**Issue by ckunkel** [SlateFoundation/slate-cbl#417]
The Standard Overview window, when looking as a student, does not show ratings, competency or standard. This does not occur when looking at a student view when logged in as a teacher. 

![screen shot 2018-01-22 at 4 12 48 pm](https://user-images.githubusercontent.com/5123794/35244706-1ac8d1d2-ff8f-11e7-8020-1c3fd4e076e3.png)

**Comment by themightychris** [comment]
Fixed in a5c5a52bf0db65a086217fcb2a7f51b0bfd11b70

**Comment by themightychris** [comment]
Builds deployed to cbl-qa
