### ISSUE TITLE
Refine styling of Slate.cbl.view.demonstrations.StudentSkillPanel

### ISSUE THREAD

**Issue by themightychris** [SlateFoundation/slate-cbl#418]
The layout has been redone and simplified a bit, and currently looks like this in the `develop` branch:
![image](https://user-images.githubusercontent.com/458494/35293397-8ac5140c-0041-11e8-9ccb-0de36a39ed22.png)

It used to look like this:
![image](https://user-images.githubusercontent.com/458494/35293447-b2319c9a-0041-11e8-8842-3c3b50f0fa12.png)

The footer buttons and student selector will be coming back in `SlateDemonstrationsTeacher`'s use of the window, but this is what it will stay like for `SlateDemonstrationsStudent`'s

**Comment by ryon** [comment]
It looks like this was already fixed?

From /SlateDemonstrationsTeacher/?apiHost=cbl-develop.dev01.slatepowered.net#MIDMATH/section:SCI-001:The+Abernathii:
![screen shot 2018-01-26 at 6 03 32 pm](https://user-images.githubusercontent.com/1154929/35464322-431e817c-02c3-11e8-82bc-be496b2cfc88.png)

I guess I'd like to get the skill list on the bottom flush with the edges again (need to override the `bodyPadding` on the window and apply padding to a container for the top components instead).

**Comment by themightychris** [comment]
I just logged that issue you called out in #420

**Comment by themightychris** [comment]
Ohh I think I added that body padding to the base class today while working on other uses of it

**Comment by themightychris** [comment]
@ckunkel can you review and close?

**Comment by ckunkel** [comment]
Looks good.
