### ISSUE TITLE
Student header link doesn't match cell size

### ISSUE THREAD

**Issue by themightychris** [SlateFoundation/slate-cbl#419]
When you roll over names in a view where the row wrapped to two lines, the hover effect on links doesn't fill the cell for the names that stay on one line:

<img width="338" alt="screen shot 2018-01-26 at 7 18 46 pm" src="https://user-images.githubusercontent.com/458494/35465956-d9a8dfca-02cd-11e8-8526-7521678a6160.png">

**Comment by katjost** [comment]
This was resolved and is working properly.
