### ISSUE TITLE
Can not select a second competency

### ISSUE THREAD

**Issue by ckunkel** [SlateFoundation/slate-cbl#421]
On the QA site, when selecting a second competency to add to the demonstration, the following error results and the second competency is not loaded. The first one loads correctly. 

![screen shot 2018-02-06 at 12 09 07 pm](https://user-images.githubusercontent.com/5123794/35873069-a8df4eee-0b36-11e8-8e61-3e5cd954bd06.png)

**Comment by themightychris** [comment]
This is fixed on cbl-qa now by making a new release of the slate-core-data package: https://github.com/SlateFoundation/slate-core-data/releases/tag/v1.1.2
