### ISSUE TITLE
Demonstration can be submitted without required information

### ISSUE THREAD

**Issue by ckunkel** [SlateFoundation/slate-cbl#423]
On the QA site, demonstrations can be submitted without Experience Type, Name of Experience or Performance Task. All of these fields are required by default, though they could be set to not required.

**Comment by themightychris** [comment]
@ckunkel do you recall which schools have configured different requirements / defaults or wanted to?

**Comment by ckunkel** [comment]
@themightychris New Foundations is the only one that did not require it, I believe.

**Comment by themightychris** [comment]
This is folded into #435
