### ISSUE TITLE
Styling of slider on demonstration window

### ISSUE THREAD

**Issue by ckunkel** [SlateFoundation/slate-cbl#424]
The default position on the slider shows both N/A and X when you move to another number. Only the X should be seen on the slider. When the selector returns to that position, it should show the N/A. 
![screen shot 2018-02-06 at 12 15 40 pm](https://user-images.githubusercontent.com/5123794/35873426-aea35658-0b37-11e8-8b98-e4fa8c38d223.png)

**Comment by katjost** [comment]
This was fixed.
