### ISSUE TITLE
Task export updated logic

### ISSUE THREAD

**Issue by ckunkel** [SlateFoundation/slate-cbl#426]
Currently the task export pulls the ExperienceType from the cbl_student_tasks table, which as it stands can not be edited. It is created when the task is created and then the task itself can be edited but not the student_task. The correct logic would be for the student_task field to be Null by default and only filled if only that student's task is edited. 

The export would then need to be updated to check the student_task record and if it has a value, use it. If it does not, it would use the ExperienceType form the cbl_task table.

**Comment by katjost** [comment]
This was fixed.
