### ISSUE TITLE
Transition brings some scores forward into the next level

### ISSUE THREAD

**Issue by ckunkel** [SlateFoundation/slate-cbl#43]
Recreate by completing all evidence requirements in a competency at low levels so that the level does not advance. Then, log new demonstrations at a high level to increase the average score. For example, log all two 8s for each standard in a competency and then log a third demonstration with every standard as a 12. 

Result: Some of the demonstrations carry over to the next level.

**Comment by themightychris** [comment]
fixed with 1309767eaac4e948e75fcb892481bab315f5e0c8
