### ISSUE TITLE
Standard Overview window does not update after submission/edit

### ISSUE THREAD

**Issue by ckunkel** [SlateFoundation/slate-cbl#433]
After submitting a new demonstration or editing an existing one, the Standard Overview window does not update and a full refresh of the screen is required to see the changed data. This should be instantaneous both in the window and in the grid. 

Currently, on delete, the grid is updated but the Standard Overview window retains the log both immediately and when you reopen it directly after. 

If you open a different Standard Overview window for a different skill or student, then open the skill that just had a demonstration deleted, the deleted demonstration is gone, so this only applies to immediately opening a skill directly after the update.

**Comment by themightychris** [comment]
Same thing happens when overrides are logged too. Monitoring the `StudentCompetency` store for updates should precisely indicate when any type of change happens for the loaded student+skill

**Comment by themightychris** [comment]
Fixed in fd5236787f213cfad0b8e65f2dda58d070b9fe87
