### ISSUE TITLE
Review field requirements for demonstrations and tasks

### ISSUE THREAD

**Issue by themightychris** [SlateFoundation/slate-cbl#435]
Test out the workflows for creating and editing tasks and demonstrations and log here any changes that need to be made to which fields are required when and what values they need to have. Assign this task to @themightychris after you're done reviewing

**Comment by ckunkel** [comment]
Demonstration creation :
Student - required
Demonstrated date - required
Type of Experience - required
Name of Experience - required
Performance Task - required
Artifact - NOT required
Demonstrated Skills - required
Comments - NOT required

Task creation: 
Title - required
Subtask of - NOT required
Type of Experience  - required
Due date- NOT required
Expiration date - NOT required
Assigned to - Required
Standards - NOT required
Attachments - NOT required
Instructions - NOT required

**Comment by themightychris** [comment]
@ckunkel the demonstrations app right now actually has different requirements implemented currently in the form and in the backend on save, could you flesh out the exact state of what it should be too?

**Comment by ckunkel** [comment]
Above comment updated to include explicit status of all fields.

**Comment by katjost** [comment]
Closing for now. If anyone wants to change it in the future, we'll create a new issue.
