### ISSUE TITLE
Ratings field doesn't reset valueSkillsMap when value is reset

### ISSUE THREAD

**Issue by themightychris** [SlateFoundation/slate-cbl#439]
If a demonstration is logged with "Continue with next student" enabled, after the demonstration is saved the `value` property of the ratings field gets correctly reset to empty but `valueSkillsMap` stays populated.

It seems like `value` is getting updated in a way that bypasses `onChange` running, perhaps within the `reset` implementation. The task may be just to ensure that the `reset` implementation fully resets all internal state.

**Comment by themightychris** [comment]
Possibly related: rating values

**Comment by ckunkel** [comment]
This may be an unrelated issue that needs logged separately, but when "continuing with next student," the values for Type of Experience, Name of Experience and Performance Task are all cleared along with the ratings. They should remain (along with the competencies selected) while the ratings are cleared (as they are now).

**Comment by themightychris** [comment]
@ckunkel that is an unrelated issue that should be filled separately. I thought we discussed it before and decided clearing things were better but I might be misremembering that convo now that I think about it. Please open a sep issue with all those points
