### ISSUE TITLE
Restore global task editing

### ISSUE THREAD

**Issue by themightychris** [SlateFoundation/slate-cbl#443]
Restore the workflow for global editing of tasks

- [X] Update existing assignees lists
- [X] Update existing skills lists
- [x] Vary window title and button
- [x] Indicate demonstration form as dirty when an attachment is changed/titled/removed
- [x] Update changed attachments
- [x] Update removed attachments
- [x] Update removed StudentTask assignments after edit
- [x] Disable/hide clone field when editing an existing task
  - The fact that a task was cloned is stored now so we should show it read-only probably

**Comment by ckunkel** [comment]
@themightychris is this task supposed to complete global editing to tasks in the grid? Edits made do not propagate to student_tasks or show in the grid, so I have to assume not, but without that, this isn't testable in terms of the functionality intended. 

Further, when editing a task, the cloning workflow is not relevant so the selector should be disabled.

**Comment by themightychris** [comment]
@ckunkel the term "global" in this title is intended to isolate this issue to the task workflows that are *not* student-specific. #444 covers the student-specific end

The feedback about removing the cloning workflow during editing is a good catch though so I'll leave this open for that

**Comment by ckunkel** [comment]
@themightychris I don't understand what this is supposed to do then. Edits to the global task should update the student_tasks and show in the grid. For example, changing a due date should apply to all tasks that were not custom set for the student. Currently editing the global task has no affect on any of the assigned tasks.

**Comment by themightychris** [comment]
@ckunkel build pushed to cbl-qa server with improved handling of cloned tasks when editing
