### ISSUE TITLE
Create unified StudentTask modal for teachers

### ISSUE THREAD

**Issue by themightychris** [SlateFoundation/slate-cbl#444]
Create a new modal that combines the edit, assign, and rating windows for student tasks.

- Merge DueDate and Reassign fields
  - "Reassigned" becomes a checkbox under due date that gets checked automatically if not checked already when due date is changed
  - Once a StudentTask is saved with status=reassigned, the checkbox becomes disabled and is permanently checked. DueDate can still be changed though
- Use simple skill selector to add ratings
- Add "Remove" option to rater menu for student-level task skills and have selecting it delete any rating

**Comment by katjost** [comment]
This was done.
