### ISSUE TITLE
Error in growth calculation for exports

### ISSUE THREAD

**Issue by tgaffey** [SlateFoundation/slate-cbl#447]
The growth calculation in the competency-details and content-areas exports do not match the interface. Attached you will find one example for ID 380 as of 5/17.
![content-area](https://user-images.githubusercontent.com/39394848/40214396-78061e10-5a28-11e8-81ae-559afe53f114.PNG)
![competency-details](https://user-images.githubusercontent.com/39394848/40214397-78134e64-5a28-11e8-9cb6-cea5c99ee1e4.PNG)
![dashboard](https://user-images.githubusercontent.com/39394848/40214398-782575ee-5a28-11e8-9a35-27823aa28443.PNG)

**Comment by themightychris** [comment]
New exports hotfixed to v2 release resolve this
