### ISSUE TITLE
export scripts need to be setup at site-root/cbl/exports/

### ISSUE THREAD

**Issue by themightychris** [SlateFoundation/slate-cbl#49]
Test for compatibility with levels and make minimal changes where needed

**Comment by themightychris** [comment]
@aharley40 issues i spoted with some/all of the new export scripts that need to be addressed before this issue is closed:

- [ ] Some files are indented too far
- [ ] Some exports have Site::$debug=false commented out at the top, all export scripts need this by default for performance. If you comment it out while working on it you must revert that change before committing (and catch it when reviewing your commit)
- [ ] All the exports need to call `$sw->close();` at the end

**Comment by ckunkel** [comment]
@aharley40 
Three reports currently exist and two of them need some updating. 
/cbl/demonstrations/export-legacy?students - every skill listed 
Currently: 
Portfolio column requires single level for all demonstrations
Multi level solution: 
add a level column next to each skill column
delete the level column D titled “Portfolio”

/cbl/demonstrations/export?students - one skill specified
No changes needed

/cbl/competencies/export?students - summary by skill and competency
Currently: 
Grade level 9 for all rows
Multi level solution: 
add rows for any levels currently active (multiple rows per student but do not show levels not yet attained)
Specify the appropriate grade level in Grade Level column
e.g. if a student is in 9th grade, but has progressed to level 11 on 1 competency, they will have 3 rows (one each for 9, 10, and 11) even though the level 10 and 11 rows will be nearly empty with the exception of the 1 competency

**Comment by aharley40** [comment]
@themightychris finished adding your changes

**Comment by themightychris** [comment]
@aharley40 I don't see any commit? please be sure to reference the issue # in your commit message or post the commit ID in your comment here so it shows up in the timeline for this issue

**Comment by aharley40** [comment]
@themightychris Finished and commit https://github.com/SlateFoundation/slate-cbl/commit/790c32e4db2c78a9d1648aa238ef2c8e77b8b813

**Comment by aharley40** [comment]
@themightychris @ckunkel I've made the requested changes to the exports. Please test these commits. 
https://github.com/SlateFoundation/slate-cbl/commit/08c77efbe32968f7a37f580309601a9245530d3a
https://github.com/SlateFoundation/slate-cbl/commit/823a8c6cb99f6d47431846846a182fb2963ea3b4

**Comment by aharley40** [comment]
I will resolve remaining comments in #58

**Comment by aharley40** [comment]
@themightychris Resolved the remaining comments. Please review #85 for commits related to this issues.

**Comment by themightychris** [comment]
the code looks good to me, @ckunkel please give the output for all 3 exports a final look over, keep an eye out for anywhere levels are shown that the correct target/demonstrated level is shown

**Comment by themightychris** [comment]
@aharley40 there are two comments in here that need addressing to close this issue: https://github.com/SlateFoundation/slate-cbl/commit/08c77efbe32968f7a37f580309601a9245530d3a#commitcomment-13350065
