### ISSUE TITLE
The standard overview window doesn't update automatically after deletion

### ISSUE THREAD

**Issue by jcunn302** [SlateFoundation/slate-cbl#50]
Steps to reproduce:

1. Open teacher dashboard
2. Click a cell to open a standard overview window
3. Delete a demonstration

Actual Results: The teacher dashboard UI refreshes and removes those filled in cells, but it remains in the list. If you click delete again, you get a server error.

Expected Result: Demonstration should be removed from the list in the standard overview window

**Comment by themightychris** [comment]
@jcunn302 this issue is fixed and can be reviewed at http://dev-cbl.node0.slate.is/cbl/teacher-dashboard?students=group+class_of_2015&content-area=ELA

**Comment by jcunn302** [comment]
Looks good to me
