### ISSUE TITLE
implement growth-based promotion

### ISSUE THREAD

**Issue by themightychris** [SlateFoundation/slate-cbl#52]

**Comment by ckunkel** [comment]
This can be held off until a later release in order to speed up the current release.

**Comment by themightychris** [comment]
@ckunkel can you define what this means again within this issue? I don't remember at this point :(

**Comment by ckunkel** [comment]
Growth is defined as meeting both of the following requirements:
1.  Completed the minimum number of demonstrations required for each skill

2.  1.2 years of growth in the given competency defined as the average of the highest logs for each skill minus the average of the lowest logs for each skill 
e.g. skill 1 - 6 7 8
skill 2 - 6 6 7
skill 3 - 6 7 8
skill 4 - 7 7 8
avg (first): 6.25 avg (last): 7.75
growth = 7.75-6.25 = 1.5

**Comment by katjost** [comment]
B21 no longer wants to do this, and we don't have any other open requests for it. Closing for now.
