### ISSUE TITLE
rename skills to standards system-wide

### ISSUE THREAD

**Issue by themightychris** [SlateFoundation/slate-cbl#53]
The term "skill" and "standard" are currently used interchangeably throughout the system, making things a minefield for future developers. `Skill` was the original term but has been deprecated in favor of `Standard`.

PHP, JS, and UI code must be refactored and database migrations written and tested.

**Comment by katjost** [comment]
This was partially implemented, but new changes are needed. Closing this. New changes are needed. See #560
