### ISSUE TITLE
Create an Advanced Enrollments Dashboard to change baselines, change target levels for ratings, and edit enrollments backwards.

### ISSUE THREAD

**Issue by tgaffey** [SlateFoundation/slate-cbl#530]
Admins need to be able to remove an enrollment or graduation from the student competency table (flip backwards), manually set baselines for any level, set the level for any demonstration skill (rating).

**Comment by tgaffey** [comment]
A request just came in to remove baselines for some students that were entered manually. The school then wanted the calculated baseline to be displayed. Does that calculation happen automatically? Would it be useful to have a button to trigger that calculation?

**Comment by themightychris** [comment]
SCHOOL-20 created to cover the demoskill level editing

**Comment by themightychris** [comment]
The scope of this ticket is now entirely captured within #744
