### ISSUE TITLE
Student task default filtering

### ISSUE THREAD

**Issue by tgaffey** [SlateFoundation/slate-cbl#535]
Change 1
When a student switches from the default view to the section specific view, they should see all tasks except archived. This was explicitly documented in a previous issue when filtering was updated. I am wondering if "default view" was understood (see definition below).

Change 2
In the default view, when a subtask is due, past due, or in revision, the parent task should never be filtered out.

Default view is defined as the view studens see after clicking on the Task Dashboard link but before choosing a section from the drop down menu.

**Comment by themightychris** [comment]
## Change 1

Current state:

![image](https://user-images.githubusercontent.com/458494/98719359-a6a9ab00-235d-11eb-9249-1e3d6e49aee7.png)

Desired state:

![image](https://user-images.githubusercontent.com/458494/98719328-9b567f80-235d-11eb-9ad1-d499e83b0b5d.png)

## Change 2

Need to always show parent task when filter includes a child task

**Comment by katjost** [comment]
This was completed.
