### ISSUE TITLE
audit codebase

### ISSUE THREAD

**Issue by themightychris** [SlateFoundation/slate-cbl#55]
- Search for TODO comments
- Strip frontend console.log calls
- Find and remove deprecated API endpoints
- Audit controller permissions
- Eliminate old PHP array syntax
- Eliminate leading commas in PHP and JS
- Inspect dev-cbl for unmerged upstream overrides
- Sweep trailing commas and whitespace

**Comment by aharley40** [comment]
Eliminated old PHP array syntax
