### ISSUE TITLE
create migration script to graduate already-ready students to level 10

### ISSUE THREAD

**Issue by themightychris** [SlateFoundation/slate-cbl#56]
move completion evaluation code  in DemonstrationSkill/afterRecordSave handler to a Competency member function that the migration script can use too.

Maybe instead of a migration script it is a simple tool any admin can use to:
- Scan for and list students eligible for advancements they haven't gotten
- Scan for and list students with advancements they no longer qualify for
- Auto-advance students with missing advancements
- In the future: Un-advance students with missing qualifications

**Comment by ckunkel** [comment]
@aharley40 
Scan for students that have met ALL of the following performance criteria on any competency
Completed the minimum number of demonstrations required for each skill
Average score of competency is above the threshold amount (this # is already calculated and displayed in the competency row)

Scan for students that have met ALL of the following growth criteria on any competency
Completed the minimum number of demonstrations required for each skill
1.2 years of growth in the given competency defined as the average of the highest logs for each skill minus the average of the lowest logs for each skill 
e.g. skill 1 - 6 7 8
skill 2 - 6 6 7
skill 3 - 6 7 8
skill 4 - 7 7 8
avg (first): 6.25 avg (last): 7.75
growth = 7.75-6.25 = 1.5

If EITHER a OR b has been met, they should be promoted to level 10 in the completed competencies

***Getting final confirmation on this, so do not yet include this logic***If additional logs exist above the minimum required demonstrations, they DO NOT carry over (even if they’re rated as at the just promoted to level or higher)

**Comment by themightychris** [comment]
@aharley40 the logic for evaluating if a student has completed a level is already implemented in this event handler: https://github.com/SlateFoundation/slate-cbl/blob/development/event-handlers/Slate/CBL/Demonstrations/DemonstrationSkill/afterRecordSave/50_complete-competency.php

Rather than reimplement it, do some refactoring to move that logic to a new method `StudentCompetency::isCurrentLevelComplete($Student, $Competency)`. The last part (`$completion['currentLevel'] < $Competency->getMaximumTargetLevel()`) wouldn't be part of that method, as that tests not if the current level is complete but if there is a next level to move them to

@ckunkel @aharley40 growth-based promotion hasn't been implemented yet and was pushed to the 0.3.1 milestone (see #52) -- it should NOT be implemented here unless we're going to move #52 to this release and add it to the core `isCurrentLevelComplete` method.

So @aharley40 the first phase of this issue will consist of
[ ] Move the isCurrentLevelComplete logic from the event handler to a sharable method
[ ] Write a script that runs this against every student+competency combination and can show the StudentCompetency records it would create in a pretend mode before being run for real to save them

Ignore the 2nd part of the issue description where i said "Maybe instead...". We're just going to bare-bones this for now with a tool we'll run manually so it doesn't need to be user-friendly. Essentially all it is doing is back-filling what that event handler would have done if it was around when the existing records got created

Also for clarification, StudentCompetency records get created when a student *begins* a level, not when they complete it. So essentially we're not recording that they've completed their current level but enrolling them in the next level which implicitely means they've completed the lower levels

**Comment by ckunkel** [comment]
@themightychris Not including growth makes sense for now since its not yet in the app as it would cause confusion when we promote some and then not others that complete it later with adequate growth.

**Comment by themightychris** [comment]
@ckunkel the way I see the script being implemented,it would just show us all the students that can be graduated to the next level but haven't been. So we could run it again later if the completion logic changes and use it to graduate any students that are newly qualified by the changed logic

**Comment by aharley40** [comment]
@themightychris @ckunkel Finished. Test at /cbl/graduation. https://github.com/SlateFoundation/slate-cbl/commit/78a37d2a53f50717c56a17f04c19fd0e3714c172

**Comment by ckunkel** [comment]
@themightychris Because this was implemented on a site that already has level progression, it's impossible to test except for level 12 completion. You suggested putting it live on one of the schools' staging sites and copying over their data. Let me know when and where it's ready to test.

**Comment by themightychris** [comment]
@aharley40 please address https://github.com/SlateFoundation/slate-cbl/commit/4519a34b3fcd94053ee31d16f5499197f88e3c3f#commitcomment-13380336

**Comment by aharley40** [comment]
@themightychris I address the changes to https://github.com/SlateFoundation/slate-cbl/commit/4519a34b3fcd94053ee31d16f5499197f88e3c3f#commitcomment-13380336 in https://github.com/SlateFoundation/slate-cbl/commit/89b13b4ef1e963b02ceac1a2987d61df541dea6b
