### ISSUE TITLE
refactor student dashboard sass

### ISSUE THREAD

**Issue by themightychris** [SlateFoundation/slate-cbl#60]
The SASS for the student dashboard is in site-root/sass/student-dashboard.scss, making it part of the site's compass build system rather than the CBL tool's and preventing it from using the same variables as the teacher dashboard

Since the student dashboard has been converted to components in the slate-cbl package (`Slate.cbl.view.student.Dashboard`, `Slate.cbl.view.student.CompetencyCard`, and `Slate.cbl.view.student.RecentProgress`), the sass should be refactored into the slate-cbl/sass directory, separated by subcomponent

- [ ] Delete `site-root/sass/student-dashboard.scss`
- [ ] Revert SlateFoundation/slate-cbl@4933fc5549a6873d99f350beee4b1d83273195ac

**Comment by themightychris** [comment]
@ryon is this considered done or still in progress?

**Comment by ryon** [comment]
@themightychris Done now. Still should probably be updated with new prefixes eventually
