### ISSUE TITLE
missed demonstrations are getting level colors

### ISSUE THREAD

**Issue by themightychris** [SlateFoundation/slate-cbl#63]
They should be grayed out and not show their target level's color

Wrong (from dev-cbl):
![screen shot 2015-05-31 at 1 38 22 pm](https://cloud.githubusercontent.com/assets/458494/7902974/5e426dea-079b-11e5-9965-ef9ee17f0385.png)

Right (from cbl.v1):
![screen shot 2015-05-31 at 1 45 21 pm](https://cloud.githubusercontent.com/assets/458494/7902978/6ea7dd64-079b-11e5-8a84-587a457ad4d9.png)

**Comment by aharley40** [comment]
@ckunkel @themightychris  How do I create records with M or what do I search to view them?

**Comment by themightychris** [comment]
You should be able to find them if you flip through content areas, or when logging demonstrations you can click on the drag thumb and a menu will come with alt values like M

**Comment by themightychris** [comment]
@aharley40 buried the fix for this in 790c32e4db2c78a9d1648aa238ef2c8e77b8b813
