### ISSUE TITLE
Cell colors not rendering

### ISSUE THREAD

**Issue by ckunkel** [SlateFoundation/slate-cbl#66]
Default colors not rendering consistently.  For some students the colors appear but not for others.  Example attached. 

![screen shot 2015-06-01 at 12 07 06 am](https://cloud.githubusercontent.com/assets/5123794/7906100/3c26d848-07f2-11e5-8286-b4bb8e5636c5.png)

**Comment by ckunkel** [comment]
This is moved forward because it is an issue with students not enrolled in a content area, which is not relevant to our current schools.

**Comment by themightychris** [comment]
This and #67 are the same issue
