### ISSUE TITLE
Completion Percentages not Registering

### ISSUE THREAD

**Issue by ckunkel** [SlateFoundation/slate-cbl#67]
Logged demonstrations appear in the grid but do not count towards competency completion.  Color rendering also is an issue here, which may be related. 

![screen shot 2015-06-01 at 12 12 27 am](https://cloud.githubusercontent.com/assets/5123794/7906139/f6495e08-07f2-11e5-8d64-bfc5a827bb0d.png)

**Comment by ckunkel** [comment]
This is moved forward because it is an issue with students not enrolled in a content area, which is not relevant to our current schools.

**Comment by themightychris** [comment]
@ckunkel what do you think the correct solution is here? Without being enrolled first we don't know what grade level they're starting at to measure them against. At the same time though I don't think we want the system to reject demonstration data, as if we have things automatically feeding into the CBL it would be better to capture the demonstration data and have to go back letter to set the target than for the demonstration data to just get dropped. 

Maybe we could just come up with a better visual style for rendering demonstrations that are recorder by not counted against a target grade level
