### ISSUE TITLE
Comment box editing error

### ISSUE THREAD

**Issue by ckunkel** [SlateFoundation/slate-cbl#68]
From Sydney: "When I click on the Comment box in attempt to revise an existing comment, a grey space takes over most of the text field."

Video:
https://www.dropbox.com/s/v2q8f0366ytchci/SLATE%20-%20Comment%20Box%20UI%20Issue.mov?dl=0

**Comment by themightychris** [comment]
I'm not able to reproduce this, it looks like a browser specific glytch. Has it ever been reproduced outside this particular computer? It's also possible the issue disappeared for the user after a more recent browser update
