### ISSUE TITLE
Implement editing baseline

### ISSUE THREAD

**Issue by themightychris** [SlateFoundation/slate-cbl#737]
Create an initial implementation of editing baseline ratings by clicking on the existing value in the portfolio header bars:

![Screen Shot 2022-11-15 at 4 12 57 PM](https://user-images.githubusercontent.com/458494/202026399-ea436fd3-e364-4340-9d35-b2bc83c8a6ba.png)

The initial implementation can just be a modal edit dialog, Ryon will take a pass later and maybe doing something more fancy/inline

For the API call to save the change, you can either do:

- [A form POST to `/cbl/student-competencies/{identifier}/edit`](https://latest.slate-cbl.sandbox.k8s.jarv.us/api-docs#paths::cbl:student-competencies:-identifier-:edit.post)
- [A JSON array of patches POST to `/cbl/student-competencies/save`](https://latest.slate-cbl.sandbox.k8s.jarv.us/api-docs#paths::cbl:student-competencies:save.post)

In either case the body can be sparse and only provide a `BaselineRating` alongside the `ID`, and `Accept: application/json` can be used to get back a JSON response body. Whichever pattern we used for moving demonstration skills between levels is probably best to repeat

**Comment by chriscauley** [comment]
Here it is. I added a dashed underline to imply that it can be clicked on. 

![image](https://user-images.githubusercontent.com/379151/216845384-751a2fc9-ee72-4121-8e1a-215d24a0380c.png)

![image](https://user-images.githubusercontent.com/379151/216845396-4fcc9a09-9228-4f2c-931f-659a1c8e7e29.png)
