### ISSUE TITLE
Discussion: migrate to Vue 3 and/or change/drop UI toolkit?

### ISSUE THREAD

**Issue by themightychris** [SlateFoundation/slate-cbl#742]
In [comments left on the original issue to wire up the advanced portfolio manager #586](https://github.com/SlateFoundation/slate-cbl/pull/586#issuecomment-1253782178), @chriscauley questioned whether we might upgrade to Vue 3 and if BootstrapVue was more trouble than it's worth

We discussed this on a call recently:

- The only reason to stick with Vue 2 is that BootstrapVue doesn't support Vue 3 yet (though it looks like [some early support](https://bootstrap-vue.org/vue3) might be available now but it sounds hacky)
- [VueTailwind](https://www.vue-tailwind.com/) is another potential option that might be more compatible with our highly customized design system, but seems to also only primarily support Vue 2 right now
- A goal of ours is to not just provide the current dashboard, but to provide a foundation for all future dashboards (and maybe start porting some past ones) to use Vue instead of Sencha, which will involve a lot of complex forms and modals and tables, so there is potentially a lot of value in having a UI toolkit in place that is both easy to theme and comes with a lot of ready-to-use higher-order UI components
- We found some articles listing Vue 3 component libraries, looks like there are some good options for us to evaluate:
    - <https://backlight.dev/mastery/best-vue-component-libraries-for-design-systems>
    - <https://vue-community.org/guide/ecosystem/ui-libraries.html>
- Potentially we could try doing without any UI toolkit, but that would leave developers building future dashboards with a heavier lift to pull in basic stuff like a fancy select / sortable table / slider / modal form that are common in the Sencha apps

**Comment by chriscauley** [comment]
I tried installing vue 3 + bootstrap-vue using the vue-compat and it seems like a rabbit hole of errors. 

Personally I'd prefer to roll our own. We could start by making folders called `src/components/ui`, `src/store/ui` and `src/css/ui` which have generic components, state management, and styling. Eventually this could be turned into a separate repo (SlateFoundation/slate-ui for instance) to be used across multiple sites.

My big concern about using a UI library is that we're working with a designer. Unless the designer has bought into the UI library we'll always have to write a large amount of styling to override the design system to match the designer. Then we'll either need a separate repo to track those variations or else we'll have to re-implement every override on every site (or even multiple times on the same site).

**Comment by acouch** [comment]
Is there a middle ground where we use VueTailwind or one of the Vue3 UI libraries and use the basic components out of the box and perhaps make small tweaks to make it close to the design? Are we obligated to stick pixel, perfect to the design?

**Comment by themightychris** [comment]
We decided to move forward with Vuetify. Cauley will wrap #737 in a simple way and then convert the dashboard to Vuetify
