### ISSUE TITLE
Override to Promotion - rendering issue

### ISSUE THREAD

**Issue by ckunkel** [SlateFoundation/slate-cbl#80]
When Overriding a number of cells to force a promotion, the display retains the overrides that were logged at the previous level. In the screen shot below, all five of the Overrides for Brittany Clay were logged at level 9 but remained when it rolled over. 

<img width="1193" alt="screen shot 2015-11-03 at 4 56 07 pm" src="https://cloud.githubusercontent.com/assets/5123794/10922886/ce1347f4-824b-11e5-8398-683cdea1d9fa.png">

After refreshing, all are dropped except the final Override that was logged (in this case Cite Evidence). 

<img width="1144" alt="screen shot 2015-11-03 at 4 57 40 pm" src="https://cloud.githubusercontent.com/assets/5123794/10922918/05ef9128-824c-11e5-9b45-329700da23b7.png">

The log is counting as a level 10 override in the Standard Overview window. 

<img width="731" alt="screen shot 2015-11-03 at 4 58 34 pm" src="https://cloud.githubusercontent.com/assets/5123794/10922952/2e10fb74-824c-11e5-8597-79cfe6773495.png">

**Comment by themightychris** [comment]
@ckunkel can you verify whether this is still an issue?
