### ISSUE TITLE
# of demonstrations doesn't agree with Competency Overview window

### ISSUE THREAD

**Issue by ckunkel** [SlateFoundation/slate-cbl#81]
When viewing details of a skill already completed at level 10, only three demonstrations show, which is clearly incorrect. 

In this example, the first two demonstrations should have been logged on level 9 and then only the override at level 10. 
<img width="1409" alt="screen shot 2015-11-05 at 7 25 38 am" src="https://cloud.githubusercontent.com/assets/5123794/10968499/9b91386e-838f-11e5-91ee-1e49072307fe.png">

In this example, two logs show in the Competency Overview, but one shows at level 10, which should mean that 3 have been logged. 
<img width="1245" alt="screen shot 2015-11-05 at 7 35 47 am" src="https://cloud.githubusercontent.com/assets/5123794/10968537/e0528b60-838f-11e5-831b-5142cf2bc98c.png">

**Comment by themightychris** [comment]
@ckunkel can you verify whether this is still an issue
