### ISSUE TITLE
Server error

### ISSUE THREAD

**Issue by ckunkel** [SlateFoundation/slate-cbl#83]
When loading a Standard Overview, a 403 server error results. The window opens, but the server error window also appears but does not show the details.

<img width="1339" alt="screen shot 2015-11-15 at 10 57 08 pm" src="https://cloud.githubusercontent.com/assets/5123794/11174046/832bb7d0-8bec-11e5-8efe-1719fbd27864.png">

<img width="1257" alt="screen shot 2015-11-15 at 11 00 09 pm" src="https://cloud.githubusercontent.com/assets/5123794/11174059/a6d8611a-8bec-11e5-88b2-dad36cce3711.png">

**Comment by themightychris** [comment]
Fixed in 74f7eb272096f6366a09e85b868fc6941d340038
