### ISSUE TITLE
Merge New Reports upstream

### ISSUE THREAD

**Issue by ckunkel** [SlateFoundation/slate-cbl#85]
Demonstrations and demonstrations-legacy reports have been updated to include demonstration IDs. demonstrations-legacy has also had teacher name added for purposes of queries that B21 wants to make about task completion percentages by standard and by teacher. 

These changes have also been made on Allentown, but should be merged upstream and pushed back down to all CBL instances. 

Demonstrations-legacy code: http://staging.fr.b21.slatepowered.net/develop#/_parent/site-root/cbl/exports/demonstrations-legacy.php

Demonstrations code: http://staging.fr.b21.slatepowered.net/develop#/site-root/cbl/exports/demonstrations.php

**Comment by katjost** [comment]
Met on 3/2 and decided to close this.
