### ISSUE TITLE
Theme standard complete checkboxes for student dashboard

### ISSUE THREAD

**Issue by themightychris** [SlateFoundation/slate-cbl#89]
Checkbox indicators have been enabled next to each student standard to indicate where all required demonstrations have bene completed:

![image](https://cloud.githubusercontent.com/assets/458494/12870739/a768fde0-cd20-11e5-9238-822bde3aa5a2.png)

Positioning needs to be fixed, and the `is-checked` class needs to be honored

**Comment by ryon** [comment]
@themightychris The slate-cbl repo seems to be mostly empty for this view, and on http://dev-cbl.node0.slate.is/ I'm having trouble getting anything to load. Do I need to point to a data set on another site?

**Comment by ryon** [comment]
OK @themightychris this is updated on http://dev-cbl.node0.slate.is/. Updated site Sass, HTML template and view code. You need jsdebug=1 to see changes.

**Comment by themightychris** [comment]
Committed in 61989e0
