### ISSUE TITLE
setup siesta testing suite

### ISSUE THREAD

**Issue by themightychris** [SlateFoundation/slate-cbl#90]
- [x] setup basic siesta sanity test to verify framework is loaded
- [ ] create series of tests that check that rowsStore and columnsStore return correct counts and the `update` event has been fired exactly once with every combination of instantiation, store configuration, and rendering happeing in different orders and groupings

**Comment by aliyeysides** [comment]
I have the checks against instantiation and store configuration but not sure if I understand that last 'rendering' part. I have a check for component visibility which fires after render but idt that's what you wanted

**Comment by themightychris** [comment]
@aliyeysides in the current test, `renderTo: Ext.getBody()` is provided to Ext.create, meaning the component is rendered immediately during instantiation and doesn't have to go through a state of being created but not yet rendered. Create tests where it is created without renderTo, and then call `aggregrid.setRenderTo(Ext.getBody())` later

**Comment by themightychris** [comment]
@aliyeysides additionally I left you a bunch of comments on the code in #93
