### ISSUE TITLE
Mockup stores for AggregridExample

### ISSUE THREAD

**Issue by themightychris** [SlateFoundation/slate-cbl#94]
Define 3 standalone store classes in the AggregridExample app, instantiate them through the `stores` config for the Application, and pass them into the aggregrid via their global storemgr id

Create a store for columns called StudentsStore, a store for rows called TimePeriodsStore, and a store for data called AbsencesStore

Fill each store with a healthy amount of made up records, make sure columns and rows render

**Comment by aliyeysides** [comment]
Continued the work on features/siesta branch
